# cli tools
brew 'coreutils'
brew 'dockutil'
brew 'git'
brew 'git-lfs'
brew 'go'
brew 'git'
brew 'mitmproxy'
brew 'python'
brew 'rbenv'
brew 'tree'
brew 'wget'
brew 'youtube-dl'
brew 'zsh'

# gui apps
cask '1password'
cask 'dash'
cask 'discord'
cask 'filezilla'
cask 'google-chrome'
cask 'lepton'
cask 'macdown'
cask 'sourcetree'
cask 'the-unarchiver'
cask 'visual-studio-code'
